### PR TITLE
Misc changes

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by rtissera** [comment]
Lots of change here.
Not I am not willing to merge, can you provide a bil more details and on which platforms it was tested ?
Thanks for the work :)

**Comment by Sanaki** [comment]
While I can't specify anything further, I can verify it builds fine on x86_64 Linux (Mint 19.3) and the benchmark tool does its job. Fed it one of my heavier chds to test against. Could use a simple help blurb on attempting to run it without any args though.
```
chdr-benchmark "Xenosaga Episode I - Der Wille zur Macht (USA).chd"

libchdr benchmark tool....
Read 1532329984 bytes in 351.693642 seconds
Rate is 4.155161 MB/s
```

**Comment by scribam** [comment]
Tests done:
- compilations of the 3 targets (chdr, chdr-static and chdr-benchmark) on Linux (GCC + Clang) and Windows (MSVC + Mingw-w64)
- run chdr-benchmark with a chd file on Linux (GCC + Clang) and Windows (MSVC + Mingw-w64)
- chdr-static integration with Flycast : https://github.com/scribam/flycast/actions/runs/1404347867

**Comment by rtissera** [comment]
Thanks for the details and testing, let's merge.

**Pull request merged**
