### PR TITLE
Add large file support

### LINKED ISSUE #40: Loading CHD files >2GiB?
I can't seem to load CHD files larger than 2GiB, all I get is `CHDERR_DECOMPRESSION_ERROR`, I used cmake and VS2019 x64 build.
Everything compiles fine and loading smaller CHD files seems to work.

### PR DESCRIPTION
**Pull request by siddhartha77**
This adds cross platform large file support and will close #40.

### CODE REVIEW

**Comment by rtissera** [comment]
Merged, thanks.
How is the CHD work going with PCSX2 and other emulators you are adding to ?

**Comment by CookiePLMonster** [comment]
@rtissera `long p = core_ftell(f);` will still truncate values, at least on Windows where `long` is 32-bit. I am guessing `long long` should have been used instead (on all platforms).

**Comment by rtissera** [comment]
Thanks.
Can you PR a fix ?

Then once everything is good I need to synchronize with libretro.

**Comment by CookiePLMonster** [comment]
Sure, I can - I checked the docs of both `_fseeki64` and `fseeko64` and they use very different types, so maybe branching the type per platform is the best way here.

Besides, the issue here seems to be a bit different `size_t` is not a good data type to store file sizes in, because of it being 32-bit when targetting 32-bit architectures. I'll need to look at this issue from a broader perspective than just the scope of this one function.

**Comment by siddhartha77** [comment]
> Merged, thanks.
> How is the CHD work going with PCSX2 and other emulators you are adding to ?

This was a quick hack here, which is why I missed the different types -- good catch @CookiePLMonster! Most of the other work was getting the CMake files in order. Still waiting for the PR to be merged to the other PR.

**Comment by rtissera** [comment]
@siddhartha77 a fix for the type issue found by @CookiePLMonster is welcome when you have time to :)

**Comment by siddhartha77** [comment]
I think switching to UINT64 resolves all issues. [New PR](https://github.com/rtissera/libchdr/pull/44) submitted.

**Pull request merged**
